/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import Client.Arma;
import Peleador.Peleador;
import Peleador.Tipo;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author kokoju
 */
public class FrameClient extends javax.swing.JFrame {
    static final int DELAY = 5; // Delay para mostrar el texto en milisegundos
    private Client client;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(FrameClient.class.getName());
    static final int CANTIDAD_TIPOS = Tipo.values().length; // Para una estructura escalable, la cantidad de tipos se
                                                            // asigna como una variable final y estática

    /**
     * Creates new form FrameClient
     */
    public FrameClient() {
        initComponents();

        // Solicitar el nombre hasta que sea válido
        String name = null;
        while (name == null || name.trim().isEmpty()) {
            name = JOptionPane.showInputDialog(this, "Ingrese su nombre");

            // Si el usuario cierra la ventana, cerrar la aplicación
            if (name == null) {
                System.exit(0);
            }

            // Si el nombre está vacío, mostrar advertencia y volver a preguntar
            if (name.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "El nombre no puede estar vacío.\nPor favor, ingresa un nombre válido.",
                        "Nombre Requerido",
                        JOptionPane.WARNING_MESSAGE);
            }
        }

        this.setTitle("Cliente de " + name); // Se pone el nombre introducido como título de la ventana
        client = new Client(this, name); // Creamos un nuevo cliente
        // Inicializar el Jugador local para poder crear luchadores desde el cliente
        client.setJugador(new Jugador(this, name));

        // Configurar event listeners (fuera de initComponents para que no se borren)
        configurarEventListeners();
    }

    /**
     * Configura los event listeners para botones y labels del formulario.
     * Se llama desde el constructor para evitar que NetBeans los borre al regenerar
     * initComponents.
     */
    private void configurarEventListeners() {
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alEnviarComando();
            }
        });

        txfInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alEnviarComando();
            }
        });

        Luchador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alSeleccionarLuchador(0);
            }
        });

        Luchador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alSeleccionarLuchador(1);
            }
        });

        Luchador3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alSeleccionarLuchador(2);
            }
        });

        Luchador4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alSeleccionarLuchador(3);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaEnemyStats = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaRanking = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaStats = new javax.swing.JTextArea();
        pnlAtaqueRecibido = new javax.swing.JPanel();
        InformacionAtaqueRecibido = new javax.swing.JLabel();
        Agresor = new javax.swing.JLabel();
        pnlAtaqueEnviado = new javax.swing.JPanel();
        Atacante = new javax.swing.JLabel();
        InformacionAtaqueRealizado = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        YOURTEAM = new javax.swing.JLabel();
        Luchador2 = new javax.swing.JLabel();
        Luchador1 = new javax.swing.JLabel();
        Luchador4 = new javax.swing.JLabel();
        Luchador3 = new javax.swing.JLabel();
        nombreLuchador = new javax.swing.JLabel();
        arma1 = new javax.swing.JLabel();
        arma4 = new javax.swing.JLabel();
        arma2 = new javax.swing.JLabel();
        arma3 = new javax.swing.JLabel();
        arma5 = new javax.swing.JLabel();
        stats5 = new javax.swing.JLabel();
        stats4 = new javax.swing.JLabel();
        stats3 = new javax.swing.JLabel();
        stats2 = new javax.swing.JLabel();
        stats1 = new javax.swing.JLabel();
        txfInput = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaMessages = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);

        txaEnemyStats.setColumns(20);
        txaEnemyStats.setRows(5);
        txaEnemyStats.setFocusable(false);
        jScrollPane1.setViewportView(txaEnemyStats);

        jScrollPane2.setEnabled(false);
        jScrollPane2.setFocusable(false);
        jScrollPane2.setWheelScrollingEnabled(false);

        txaRanking.setColumns(20);
        txaRanking.setRows(5);
        txaRanking.setFocusable(false);
        jScrollPane2.setViewportView(txaRanking);
        txaRanking.getAccessibleContext().setAccessibleDescription("");
        txaRanking.getAccessibleContext().setAccessibleParent(jScrollPane1);

        jScrollPane3.setEnabled(false);
        jScrollPane3.setFocusable(false);

        txaStats.setColumns(20);
        txaStats.setRows(5);
        txaStats.setFocusable(false);
        jScrollPane3.setViewportView(txaStats);

        pnlAtaqueRecibido.setBackground(new java.awt.Color(51, 51, 51));

        InformacionAtaqueRecibido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InformacionAtaqueRecibido.setText("Último ataque recibido");

        javax.swing.GroupLayout pnlAtaqueRecibidoLayout = new javax.swing.GroupLayout(pnlAtaqueRecibido);
        pnlAtaqueRecibido.setLayout(pnlAtaqueRecibidoLayout);
        pnlAtaqueRecibidoLayout.setHorizontalGroup(
                pnlAtaqueRecibidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlAtaqueRecibidoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(InformacionAtaqueRecibido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Agresor, javax.swing.GroupLayout.PREFERRED_SIZE, 166,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        pnlAtaqueRecibidoLayout.setVerticalGroup(
                pnlAtaqueRecibidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlAtaqueRecibidoLayout.createSequentialGroup()
                                .addGroup(pnlAtaqueRecibidoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlAtaqueRecibidoLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(InformacionAtaqueRecibido))
                                        .addGroup(pnlAtaqueRecibidoLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(Agresor, javax.swing.GroupLayout.PREFERRED_SIZE, 233,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(16, Short.MAX_VALUE)));

        pnlAtaqueEnviado.setBackground(new java.awt.Color(51, 51, 51));

        InformacionAtaqueRealizado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InformacionAtaqueRealizado.setText("Último ataque realizado");

        javax.swing.GroupLayout pnlAtaqueEnviadoLayout = new javax.swing.GroupLayout(pnlAtaqueEnviado);
        pnlAtaqueEnviado.setLayout(pnlAtaqueEnviadoLayout);
        pnlAtaqueEnviadoLayout.setHorizontalGroup(
                pnlAtaqueEnviadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                pnlAtaqueEnviadoLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(InformacionAtaqueRealizado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132,
                                                Short.MAX_VALUE)
                                        .addComponent(Atacante, javax.swing.GroupLayout.PREFERRED_SIZE, 160,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap()));
        pnlAtaqueEnviadoLayout.setVerticalGroup(
                pnlAtaqueEnviadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlAtaqueEnviadoLayout.createSequentialGroup()
                                .addGroup(pnlAtaqueEnviadoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlAtaqueEnviadoLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(InformacionAtaqueRealizado))
                                        .addGroup(pnlAtaqueEnviadoLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(Atacante, javax.swing.GroupLayout.PREFERRED_SIZE, 230,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(25, Short.MAX_VALUE)));

        pnlMenu.setBackground(new java.awt.Color(51, 51, 51));

        YOURTEAM.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        YOURTEAM.setForeground(new java.awt.Color(255, 255, 255));
        YOURTEAM.setText("YOUR TEAM");

        Luchador1.setBackground(new java.awt.Color(255, 51, 51));

        Luchador3.setBackground(new java.awt.Color(255, 51, 51));

        nombreLuchador.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nombreLuchador.setForeground(new java.awt.Color(255, 255, 255));
        nombreLuchador.setText("nombre del heroe");

        arma1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arma1.setForeground(new java.awt.Color(255, 255, 255));
        arma1.setText("arma1");

        arma4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arma4.setForeground(new java.awt.Color(255, 255, 255));
        arma4.setText("arma4");

        arma2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arma2.setForeground(new java.awt.Color(255, 255, 255));
        arma2.setText("arma2");

        arma3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arma3.setForeground(new java.awt.Color(255, 255, 255));
        arma3.setText("arma3");

        arma5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arma5.setForeground(new java.awt.Color(255, 255, 255));
        arma5.setText("arma5");

        stats5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stats5.setForeground(new java.awt.Color(204, 255, 255));
        stats5.setText("stats5");

        stats4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stats4.setForeground(new java.awt.Color(204, 255, 255));
        stats4.setText("stats4");

        stats3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stats3.setForeground(new java.awt.Color(204, 255, 255));
        stats3.setText("stats3");

        stats2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stats2.setForeground(new java.awt.Color(204, 255, 255));
        stats2.setText("stats2");

        stats1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stats1.setForeground(new java.awt.Color(204, 255, 255));
        stats1.setText("stats1");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
                pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(YOURTEAM)
                                        .addComponent(nombreLuchador)
                                        .addGroup(pnlMenuLayout.createSequentialGroup()
                                                .addGroup(pnlMenuLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Luchador1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(arma3)
                                                        .addComponent(arma4)
                                                        .addComponent(arma2)
                                                        .addComponent(arma1)
                                                        .addComponent(arma5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pnlMenuLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(stats1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(pnlMenuLayout.createSequentialGroup()
                                                                .addGroup(pnlMenuLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addGroup(pnlMenuLayout.createSequentialGroup()
                                                                                .addComponent(Luchador2,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        143,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(Luchador3,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        143,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(Luchador4,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        143,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(stats2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(stats3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(stats4,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(stats5,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addContainerGap()));
        pnlMenuLayout.setVerticalGroup(
                pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(YOURTEAM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMenuLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Luchador4, javax.swing.GroupLayout.DEFAULT_SIZE, 245,
                                                Short.MAX_VALUE)
                                        .addComponent(Luchador3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Luchador2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Luchador1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlMenuLayout.createSequentialGroup()
                                                .addComponent(nombreLuchador)
                                                .addGap(18, 18, 18)
                                                .addComponent(arma1)
                                                .addGap(18, 18, 18)
                                                .addComponent(arma2)
                                                .addGap(18, 18, 18)
                                                .addComponent(arma3)
                                                .addGap(18, 18, 18)
                                                .addComponent(arma4)
                                                .addGap(18, 18, 18)
                                                .addComponent(arma5))
                                        .addGroup(pnlMenuLayout.createSequentialGroup()
                                                .addComponent(stats1)
                                                .addGap(18, 18, 18)
                                                .addComponent(stats2)
                                                .addGap(18, 18, 18)
                                                .addComponent(stats3)
                                                .addGap(18, 18, 18)
                                                .addComponent(stats4)
                                                .addGap(18, 18, 18)
                                                .addComponent(stats5)))
                                .addContainerGap(14, Short.MAX_VALUE)));

        btnSend.setBackground(new java.awt.Color(0, 204, 0));
        btnSend.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnSend.setText("SEND");

        jScrollPane4.setEnabled(false);
        jScrollPane4.setFocusable(false);
        jScrollPane4.setWheelScrollingEnabled(false);

        txaMessages.setColumns(20);
        txaMessages.setRows(5);
        txaMessages.setFocusable(false);
        jScrollPane4.setViewportView(txaMessages);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane3,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(pnlAtaqueRecibido,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(pnlAtaqueEnviado,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(txfInput))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 469,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pnlMenu,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(pnlAtaqueRecibido,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(pnlAtaqueEnviado,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(12, 12, 12)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txfInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 93,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameClient().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agresor;
    private javax.swing.JLabel Atacante;
    private javax.swing.JLabel InformacionAtaqueRealizado;
    private javax.swing.JLabel InformacionAtaqueRecibido;
    private javax.swing.JLabel Luchador1;
    private javax.swing.JLabel Luchador2;
    private javax.swing.JLabel Luchador3;
    private javax.swing.JLabel Luchador4;
    private javax.swing.JLabel YOURTEAM;
    private javax.swing.JLabel arma1;
    private javax.swing.JLabel arma2;
    private javax.swing.JLabel arma3;
    private javax.swing.JLabel arma4;
    private javax.swing.JLabel arma5;
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nombreLuchador;
    private javax.swing.JPanel pnlAtaqueEnviado;
    private javax.swing.JPanel pnlAtaqueRecibido;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JLabel stats1;
    private javax.swing.JLabel stats2;
    private javax.swing.JLabel stats3;
    private javax.swing.JLabel stats4;
    private javax.swing.JLabel stats5;
    private javax.swing.JTextArea txaEnemyStats;
    private javax.swing.JTextArea txaMessages;
    private javax.swing.JTextArea txaRanking;
    private javax.swing.JTextArea txaStats;
    private javax.swing.JTextField txfInput;
    // End of variables declaration//GEN-END:variables

    public void writeMessage(String msg) {
        txaMessages.append(msg + "\n");
    }

    // Getters
    public static Logger getLogger() {
        return logger;
    }

    public JButton getBtnSend() {
        return btnSend;
    }

    public JPanel getPnlAttack1() {
        return pnlAtaqueRecibido;
    }

    public JPanel getPnlAttack2() {
        return pnlAtaqueEnviado;
    }

    public JPanel getPnlMenu() {
        return pnlMenu;
    }

    public JTextArea getTxaEnemyStats() {
        return txaEnemyStats;
    }

    public JTextArea getTxaRanking() {
        return txaRanking;
    }

    public JTextArea getTxaStats() {
        return txaStats;
    }

    public JTextField getTxfInput() {
        return txfInput;
    }

    // Setters
    public void setTextTxaEnemyStats(String text) {
        this.txaEnemyStats.setText(text);
    }

    public void setTextTxaRanking(String text) {
        this.txaRanking.setText(text);
    }

    public void setTextTxaStats(String text) {
        this.txaStats.setText(text);
    }

    // UI helpers
    /**
     * Actualiza el panel de menú cuando se selecciona un luchador.
     * Muestra el nombre formateado con porcentaje de vida y las armas asignadas.
     */
    private void alSeleccionarLuchador(int index) {
        if (client == null)
            return;
        Jugador j = client.getJugador();
        if (j == null)
            return;
        Peleador[] arr = j.getPeleadores();
        if (index < 0 || index >= arr.length)
            return;
        Peleador p = arr[index];
        if (p == null) {
            nombreLuchador.setText("(vacío)");
            arma1.setText("");
            arma2.setText("");
            arma3.setText("");
            arma4.setText("");
            arma5.setText("");
            stats1.setText("");
            stats2.setText("");
            stats3.setText("");
            stats4.setText("");
            stats5.setText("");
            return;
        }
        // Formatear nombre sin barras bajas y con mayúsculas, más tipo con color y vida
        // en %
        String nombreFormateado = formatearNombreLuchador(p.getNombre());
        int vidaPorcentaje = p.getVida();
        String colorTipo = getColorTipo(p.getTipo());
        String tipoStr = p.getTipo() != null ? p.getTipo().toString() : "";
        nombreLuchador.setText("<html>" + nombreFormateado +
                " <font color='" + colorTipo + "'>[" + tipoStr + "]</font>" +
                " (" + vidaPorcentaje + "%)</html>");
        Arma[] armas = p.getArregloArmas();
        if (armas == null || armas.length == 0) {
            arma1.setText("(sin armas)");
            arma2.setText("");
            arma3.setText("");
            arma4.setText("");
            arma5.setText("");
            stats1.setText("");
            stats2.setText("");
            stats3.setText("");
            stats4.setText("");
            stats5.setText("");
        } else {
            if (armas.length > 0 && armas[0] != null) {
                arma1.setText(armas[0].getNombre());
                stats1.setText(formatearArrayDaño(armas[0].getArregloGolpe()));
            } else {
                arma1.setText("");
                stats1.setText("");
            }
            if (armas.length > 1 && armas[1] != null) {
                arma2.setText(armas[1].getNombre());
                stats2.setText(formatearArrayDaño(armas[1].getArregloGolpe()));
            } else {
                arma2.setText("");
                stats2.setText("");
            }
            if (armas.length > 2 && armas[2] != null) {
                arma3.setText(armas[2].getNombre());
                stats3.setText(formatearArrayDaño(armas[2].getArregloGolpe()));
            } else {
                arma3.setText("");
                stats3.setText("");
            }
            if (armas.length > 3 && armas[3] != null) {
                arma4.setText(armas[3].getNombre());
                stats4.setText(formatearArrayDaño(armas[3].getArregloGolpe()));
            } else {
                arma4.setText("");
                stats4.setText("");
            }
            if (armas.length > 4 && armas[4] != null) {
                arma5.setText(armas[4].getNombre());
                stats5.setText(formatearArrayDaño(armas[4].getArregloGolpe()));
            } else {
                arma5.setText("");
                stats5.setText("");
            }
        }
    }

    /**
     * Convierte un array de daños en HTML con cada valor coloreado según su tipo.
     */
    private String formatearArrayDaño(int[] daños) {
        if (daños == null || daños.length == 0)
            return "";
        StringBuilder sb = new StringBuilder();
        sb.append("<html>");
        for (int i = 0; i < daños.length; i++) {
            String color = getColorTipoPorIndice(i);
            sb.append("<font color='").append(color).append("'>");
            sb.append(daños[i]);
            sb.append("</font>");
            if (i < daños.length - 1) {
                sb.append("&nbsp;&nbsp;&nbsp;&nbsp;"); // Más espacio entre números
            }
        }
        sb.append("</html>");
        return sb.toString();
    }

    /**
     * Formatea el nombre de un luchador eliminando guiones bajos y capitalizando
     * cada palabra.
     * Ejemplo: "black_manta" -> "Black Manta"
     */
    private String formatearNombreLuchador(String nombre) {
        if (nombre == null || nombre.isEmpty())
            return "";
        String[] partes = nombre.split("_");
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < partes.length; i++) {
            if (partes[i].length() > 0) {
                sb.append(Character.toUpperCase(partes[i].charAt(0)));
                if (partes[i].length() > 1) {
                    sb.append(partes[i].substring(1).toLowerCase());
                }
            }
            if (i < partes.length - 1) {
                sb.append(" ");
            }
        }
        return sb.toString();
    }

    /**
     * Colores asignados a cada tipo de luchador.
     * Orden: FUEGO, AIRE, AGUA, TIERRA, VOLADOR, VENENO, HIELO, METAL, PSIQUICO,
     * HADA
     */
    private static final String[] COLORES_TIPO = {
            "#FF4500", // FUEGO - Naranja rojizo
            "#87CEEB", // AIRE - Celeste
            "#1E90FF", // AGUA - Azul
            "#8B4513", // TIERRA - Marrón
            "#9370DB", // VOLADOR - Púrpura medio
            "#9932CC", // VENENO - Violeta oscuro
            "#00CED1", // HIELO - Turquesa
            "#708090", // METAL - Gris pizarra
            "#FF1493", // PSIQUICO - Rosa intenso
            "#FFB6C1" // HADA - Rosa claro
    };

    /**
     * Obtiene el color hexadecimal asignado a un tipo de luchador.
     */
    private String getColorTipo(Tipo tipo) {
        if (tipo == null)
            return "#000000";
        int index = tipo.ordinal();
        if (index >= 0 && index < COLORES_TIPO.length) {
            return COLORES_TIPO[index];
        }
        return "#000000";
    }

    /**
     * Obtiene el color hexadecimal para un índice de tipo.
     */
    private String getColorTipoPorIndice(int index) {
        if (index >= 0 && index < COLORES_TIPO.length) {
            return COLORES_TIPO[index];
        }
        return "#000000";
    }

    /**
     * Procesa el comando ingresado por el usuario en el campo de texto.
     * Valida y ejecuta comandos locales o los envía al servidor según corresponda.
     */
    private void alEnviarComando() {
        String input = txfInput.getText();
        if (input == null)
            input = "";
        input = input.trim();
        if (input.isEmpty())
            return;

        String[] parts = input.split("\\s+");
        Models.Command cmd = Models.CommandFactory.getCommand(parts);
        if (cmd == null) {
            writeMessage("Comando inválido");
            return;
        }
        try {
            if (cmd.isOwnCommand()) {
                cmd.processInClient(client);
            } else {
                client.getObjectSender().writeObject(cmd);
            }
        } catch (Exception e) {
            writeMessage("Error enviando comando: " + e.getMessage());
        }
    }

    /**
     * Carga y escala la imagen de un luchador en el label correspondiente del panel
     * de menú.
     * También actualiza el nombre formateado con porcentaje de vida.
     */
    public void establecerImagenLuchador(String fighterName) {
        if (fighterName == null || fighterName.trim().isEmpty())
            return;
        String normalized = fighterName.trim().toLowerCase();
        javax.swing.ImageIcon icon = null;
        java.net.URL url = getClass().getResource("/" + normalized + ".png");
        if (url != null) {
            icon = new javax.swing.ImageIcon(url);
        } else {
            // intentar jpg como fallback
            url = getClass().getResource("/" + normalized + ".jpg");
            if (url != null)
                icon = new javax.swing.ImageIcon(url);
        }
        if (icon == null)
            return;

        // encontrar el índice del nuevo peleador y colocar la imagen en el label
        // correspondiente
        Jugador j;
        if (client != null) {
            j = client.getJugador();
        } else {
            j = null;
        }
        if (j == null)
            return;
        Peleador[] arr = j.getPeleadores();
        int index = -1;
        for (int i = 0; i < arr.length; i++) {
            Peleador p = arr[i];
            if (p != null && p.getNombre() != null && p.getNombre().trim().equalsIgnoreCase(fighterName)) {
                index = i;
                break;
            }
        }
        if (index == -1)
            return;

        javax.swing.JLabel targetLabel = null;
        if (index == 0) {
            targetLabel = Luchador1;
        } else if (index == 1) {
            targetLabel = Luchador2;
        } else if (index == 2) {
            targetLabel = Luchador3;
        } else if (index == 3) {
            targetLabel = Luchador4;
        }
        if (targetLabel == null)
            return;

        int w = targetLabel.getWidth();
        int h = targetLabel.getHeight();
        if (w <= 0 || h <= 0) {
            java.awt.Dimension pref = targetLabel.getPreferredSize();
            if (pref != null) {
                w = pref.width;
                h = pref.height;
            } else {
                w = icon.getIconWidth();
                h = icon.getIconHeight();
            }
        }

        java.awt.Image scaled = icon.getImage().getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon scaledIcon = new javax.swing.ImageIcon(scaled);
        targetLabel.setIcon(scaledIcon);
        // también mostrar el nombre formateado con vida
        Peleador p = arr[index];
        String nombreFormateado = formatearNombreLuchador(fighterName);
        int vidaPorcentaje = (p != null) ? p.getVida() : 100;
        nombreLuchador.setText(nombreFormateado + " (" + vidaPorcentaje + "%)");

        // Actualizar la vista de armas seleccionando automáticamente este luchador
        if (j != null) {
            alSeleccionarLuchador(index);
        }
    }

    // Métodos para actualizar paneles de ataque
    /**
     * Actualiza el panel de ataque realizado con la imagen del peleador atacante,
     * información del objetivo, arma usada y daño total causado.
     */
    public void actualizarAtaqueRealizado(String nombrePeleador, String nombreArma, String jugadorObjetivo,
            int dañoTotal, int golpesExitosos) {
        // Establecer imagen del peleador atacante
        javax.swing.ImageIcon icon = cargarImagenPeleador(nombrePeleador);
        if (icon != null) {
            int w = Atacante.getWidth();
            int h = Atacante.getHeight();
            if (w <= 0)
                w = Atacante.getPreferredSize().width;
            if (h <= 0)
                h = Atacante.getPreferredSize().height;
            if (w <= 0)
                w = 100;
            if (h <= 0)
                h = 100;
            java.awt.Image scaled = icon.getImage().getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
            Atacante.setIcon(new javax.swing.ImageIcon(scaled));
        }
        // Mostrar información del ataque con daño total
        StringBuilder sb = new StringBuilder();
        sb.append("<html>");
        String nombreFormateado = formatearNombreLuchador(nombrePeleador);
        sb.append("<b>").append(nombreFormateado).append("</b> atacó a <b>").append(jugadorObjetivo).append("</b><br>");
        sb.append("Arma: <b>").append(nombreArma).append("</b><br><br>");
        sb.append("<font size='+1'><b>Daño total causado: ").append(dañoTotal).append("</b></font><br>");
        sb.append("Golpes exitosos: <b>").append(golpesExitosos).append("</b>");
        sb.append("</html>");
        InformacionAtaqueRealizado.setText(sb.toString());
    }

    /**
     * Actualiza el panel de ataque recibido con la imagen del agresor,
     * información del atacante, arma usada y el daño individual recibido por cada
     * luchador.
     */
    public void actualizarAtaqueRecibido(String nombreJugador, String nombreAgresor, String nombreArma,
            int[] dañosPorLuchador) {
        // Establecer imagen del agresor
        javax.swing.ImageIcon icon = cargarImagenPeleador(nombreAgresor);
        if (icon != null) {
            int w = Agresor.getWidth();
            int h = Agresor.getHeight();
            if (w <= 0)
                w = Agresor.getPreferredSize().width;
            if (h <= 0)
                h = Agresor.getPreferredSize().height;
            if (w <= 0)
                w = 100;
            if (h <= 0)
                h = 100;
            java.awt.Image scaled = icon.getImage().getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
            Agresor.setIcon(new javax.swing.ImageIcon(scaled));
        }
        // Mostrar información completa del ataque recibido
        StringBuilder sb = new StringBuilder();
        sb.append("<html>");
        sb.append("<b>").append(nombreJugador).append("</b> atacó con <b>")
                .append(formatearNombreLuchador(nombreAgresor)).append("</b><br>");
        sb.append("Arma: <b>").append(nombreArma).append("</b><br><br>");

        Jugador j = null;
        if (client != null) {
            j = client.getJugador();
        }
        int dañoTotal = 0;
        if (j != null && dañosPorLuchador != null) {
            Peleador[] peleadores = j.getPeleadores();
            for (int i = 0; i < dañosPorLuchador.length && i < peleadores.length; i++) {
                if (peleadores[i] != null) {
                    String nombreFormateado = formatearNombreLuchador(peleadores[i].getNombre());
                    String colorTipo = getColorTipo(peleadores[i].getTipo());
                    String tipoStr = peleadores[i].getTipo() != null ? peleadores[i].getTipo().toString() : "";
                    int daño = dañosPorLuchador[i];
                    dañoTotal += daño;
                    String estado = daño >= 60 ? " <b>¡Golpe!</b>" : " (Falló)";
                    sb.append(nombreFormateado);
                    sb.append(" <font color='").append(colorTipo).append("'>[").append(tipoStr).append("]</font>");
                    sb.append(" recibió <b>").append(daño).append("</b>").append(estado);
                    sb.append("<br>");
                }
            }
        }
        sb.append("<br><b>Daño total recibido: ").append(dañoTotal).append("</b>");
        sb.append("</html>");
        InformacionAtaqueRecibido.setText(sb.toString());

        // Actualizar vida de luchadores en el panel de menú
        actualizarVidasLuchadores();
    }

    /**
     * Actualiza las vidas mostradas de los luchadores después de recibir un ataque.
     */
    private void actualizarVidasLuchadores() {
        if (client == null)
            return;
        Jugador j = client.getJugador();
        if (j == null)
            return;
        Peleador[] peleadores = j.getPeleadores();

        // Actualizar los nombres en los labels con las vidas actualizadas
        javax.swing.JLabel[] labels = { Luchador1, Luchador2, Luchador3, Luchador4 };
        for (int i = 0; i < peleadores.length && i < labels.length; i++) {
            if (peleadores[i] != null) {
                String nombre = formatearNombreLuchador(peleadores[i].getNombre());
                int vida = peleadores[i].getVida();
                labels[i].setToolTipText(nombre + " (" + vida + "%)");
            }
        }
    }

    /**
     * Carga la imagen de un peleador desde resources (.png o .jpg).
     * Retorna null si no se encuentra la imagen.
     */
    private javax.swing.ImageIcon cargarImagenPeleador(String nombrePeleador) {
        if (nombrePeleador == null || nombrePeleador.trim().isEmpty())
            return null;
        String normalized = nombrePeleador.trim().toLowerCase();
        java.net.URL url = getClass().getResource("/" + normalized + ".png");
        if (url != null) {
            return new javax.swing.ImageIcon(url);
        }
        url = getClass().getResource("/" + normalized + ".jpg");
        if (url != null) {
            return new javax.swing.ImageIcon(url);
        }
        return null;
    }
}
