/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import Peleador.Tipo;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author kokoju
 */
public class FrameClient extends javax.swing.JFrame {
    static final int DELAY = 5; // Delay para mostrar el texto en milisegundos
    private Client client;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameClient.class.getName());
    static final int CANTIDAD_TIPOS = Tipo.values().length;  // Para una estructura escalable, la cantidad de tipos se asigna como  una variable final y estática
    /**
     * Creates new form FrameClient
     */
    public FrameClient() {
        initComponents();

        // Solicitar el nombre hasta que sea válido
        String name = null;
        while (name == null || name.trim().isEmpty()) {
            name = JOptionPane.showInputDialog(this, "Ingrese su nombre");

            // Si el usuario cierra la ventana, cerrar la aplicación
            if (name == null) {
                System.exit(0);
            }

            // Si el nombre está vacío, mostrar advertencia y volver a preguntar
            if (name.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "El nombre no puede estar vacío.\nPor favor, ingresa un nombre válido.",
                        "Nombre Requerido",
                        JOptionPane.WARNING_MESSAGE);
            }
        }

        this.setTitle("Cliente de " + name); // Se pone el nombre introducido como título de la ventana
        client = new Client(this, name); // Creamos un nuevo cliente c
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaEnemyStats = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaRanking = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaStats = new javax.swing.JTextArea();
        pnlAttack1 = new javax.swing.JPanel();
        pnlAttack2 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        YOURTEAM = new javax.swing.JLabel();
        Luchador2 = new javax.swing.JLabel();
        Luchador1 = new javax.swing.JLabel();
        Luchador4 = new javax.swing.JLabel();
        Luchador3 = new javax.swing.JLabel();
        nombreLuchador = new javax.swing.JLabel();
        arma1 = new javax.swing.JLabel();
        arma4 = new javax.swing.JLabel();
        arma2 = new javax.swing.JLabel();
        arma3 = new javax.swing.JLabel();
        txfInput = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaMessages = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);

        txaEnemyStats.setColumns(20);
        txaEnemyStats.setRows(5);
        txaEnemyStats.setFocusable(false);
        jScrollPane1.setViewportView(txaEnemyStats);

        jScrollPane2.setEnabled(false);
        jScrollPane2.setFocusable(false);
        jScrollPane2.setWheelScrollingEnabled(false);

        txaRanking.setColumns(20);
        txaRanking.setRows(5);
        txaRanking.setFocusable(false);
        jScrollPane2.setViewportView(txaRanking);
        txaRanking.getAccessibleContext().setAccessibleDescription("");
        txaRanking.getAccessibleContext().setAccessibleParent(jScrollPane1);

        jScrollPane3.setEnabled(false);
        jScrollPane3.setFocusable(false);

        txaStats.setColumns(20);
        txaStats.setRows(5);
        txaStats.setFocusable(false);
        jScrollPane3.setViewportView(txaStats);

        pnlAttack1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pnlAttack1Layout = new javax.swing.GroupLayout(pnlAttack1);
        pnlAttack1.setLayout(pnlAttack1Layout);
        pnlAttack1Layout.setHorizontalGroup(
            pnlAttack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        pnlAttack1Layout.setVerticalGroup(
            pnlAttack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        pnlAttack2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pnlAttack2Layout = new javax.swing.GroupLayout(pnlAttack2);
        pnlAttack2.setLayout(pnlAttack2Layout);
        pnlAttack2Layout.setHorizontalGroup(
            pnlAttack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        pnlAttack2Layout.setVerticalGroup(
            pnlAttack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pnlMenu.setBackground(new java.awt.Color(102, 255, 102));

        YOURTEAM.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        YOURTEAM.setText("YOUR TEAM");

        Luchador2.setText("jLabel2");
        Luchador2.setOpaque(true);

        Luchador1.setBackground(new java.awt.Color(255, 51, 51));
        Luchador1.setText("jLabel2");
        Luchador1.setOpaque(true);

        Luchador4.setText("jLabel2");
        Luchador4.setOpaque(true);

        Luchador3.setBackground(new java.awt.Color(255, 51, 51));
        Luchador3.setText("jLabel2");
        Luchador3.setOpaque(true);

        nombreLuchador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreLuchador.setForeground(new java.awt.Color(204, 0, 51));
        nombreLuchador.setText("nombre del heroe");

        arma1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arma1.setForeground(new java.awt.Color(255, 0, 102));
        arma1.setText("arma1");

        arma4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arma4.setForeground(new java.awt.Color(255, 0, 102));
        arma4.setText("arma4");

        arma2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arma2.setForeground(new java.awt.Color(255, 0, 102));
        arma2.setText("arma2");

        arma3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arma3.setForeground(new java.awt.Color(255, 0, 102));
        arma3.setText("arma3");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YOURTEAM)
                            .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addComponent(Luchador1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Luchador2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Luchador3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Luchador4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nombreLuchador)
                            .addComponent(arma3)
                            .addComponent(arma4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arma2)
                            .addComponent(arma1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(YOURTEAM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Luchador1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Luchador2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Luchador3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Luchador4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreLuchador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(arma1)
                .addGap(18, 18, 18)
                .addComponent(arma2)
                .addGap(18, 18, 18)
                .addComponent(arma3)
                .addGap(18, 18, 18)
                .addComponent(arma4)
                .addGap(16, 16, 16))
        );

        btnSend.setBackground(new java.awt.Color(0, 204, 0));
        btnSend.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnSend.setText("SEND");

        jScrollPane4.setEnabled(false);
        jScrollPane4.setFocusable(false);
        jScrollPane4.setWheelScrollingEnabled(false);

        txaMessages.setColumns(20);
        txaMessages.setRows(5);
        txaMessages.setFocusable(false);
        jScrollPane4.setViewportView(txaMessages);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlAttack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlAttack2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pnlAttack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pnlAttack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameClient().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Luchador1;
    private javax.swing.JLabel Luchador2;
    private javax.swing.JLabel Luchador3;
    private javax.swing.JLabel Luchador4;
    private javax.swing.JLabel YOURTEAM;
    private javax.swing.JLabel arma1;
    private javax.swing.JLabel arma2;
    private javax.swing.JLabel arma3;
    private javax.swing.JLabel arma4;
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nombreLuchador;
    private javax.swing.JPanel pnlAttack1;
    private javax.swing.JPanel pnlAttack2;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JTextArea txaEnemyStats;
    private javax.swing.JTextArea txaMessages;
    private javax.swing.JTextArea txaRanking;
    private javax.swing.JTextArea txaStats;
    private javax.swing.JTextField txfInput;
    // End of variables declaration//GEN-END:variables

    // Getters
    public static Logger getLogger() {
        return logger;
    }

    public JButton getBtnSend() {
        return btnSend;
    }

    public JPanel getPnlAttack1() {
        return pnlAttack1;
    }

    public JPanel getPnlAttack2() {
        return pnlAttack2;
    }

    public JPanel getPnlMenu() {
        return pnlMenu;
    }

    public JTextArea getTxaEnemyStats() {
        return txaEnemyStats;
    }

    public JTextArea getTxaRanking() {
        return txaRanking;
    }

    public JTextArea getTxaStats() {
        return txaStats;
    }

    public JTextField getTxfInput() {
        return txfInput;
    }
    
    // Setters
    public void setTextTxaEnemyStats(String text) {
        this.txaEnemyStats.setText(text);
    }
    
    public void setTextTxaRanking(String text) {
        this.txaRanking.setText(text);
    }
    
    public void setTextTxaStats(String text) {
        this.txaStats.setText(text);
    }

    public void writeMessage(String msg) {
        txaMessages.append(msg + "\n");
        
    }
    
}
